local wezterm = require("wezterm")
local act = wezterm.action
local customize_action = require("libraries.customize-actions")
local special_action = require("libraries.special-actions")
local resize_action = require("libraries.resize-actions")

local GENERATE_KEYS = {}

function GENERATE_KEYS.gen_custom_keys(mods)
    local p = mods.primary
    local s = mods.secondary
    local t = mods.tertiary

    return {
        -- Alphas:
        { key = "a", mods = p, action = special_action.SpawnProgramInNewWindow("btm") },
        { key = "b", mods = p, action = act.ScrollByPage(-1) },
        { key = "c", mods = p, action = act.CopyTo("ClipboardAndPrimarySelection") },
        { key = "d", mods = p, action = act.ScrollByPage(0.5) },
        { key = "f", mods = p, action = act.ScrollByPage(1) },
        { key = "f", mods = t, action = act.ActivatePaneDirection("Prev") },
        { key = "g", mods = p, action = act.PaneSelect({ mode = "SwapWithActiveKeepFocus" }) },
        { key = "h", mods = p, action = act.ActivatePaneDirection("Left") },
        { key = "i", mods = p, action = special_action.RenameCurrentTab },
        { key = "j", mods = p, action = act.ActivatePaneDirection("Down") },
        { key = "k", mods = p, action = act.ActivatePaneDirection("Up") },
        { key = "l", mods = p, action = act.ActivatePaneDirection("Right") },
        { key = "n", mods = p, action = act.SpawnWindow },
        { key = "o", mods = p, action = act.ShowLauncher },
        { key = "o", mods = t, action = act.OpenLinkAtMouseCursor },
        { key = "p", mods = p, action = act.ActivateCommandPalette },
        { key = "q", mods = p, action = act.QuitApplication },
        { key = "s", mods = p, action = act.ActivateCopyMode },
        { key = "t", mods = p, action = act.SpawnTab("CurrentPaneDomain") },
        { key = "u", mods = p, action = act.ScrollByPage(-0.5) },
        { key = "v", mods = p, action = act.PasteFrom("Clipboard") },
        { key = "w", mods = p, action = act.CloseCurrentTab({ confirm = true }) },
        { key = "x", mods = p, action = act.ActivateCopyMode },
        { key = "z", mods = p, action = act.TogglePaneZoomState },
        -- Numbers:
        { key = '!', mods = p, action = act.ActivateTab(0) },
        { key = '@', mods = p, action = act.ActivateTab(1) },
        { key = '#', mods = p, action = act.ActivateTab(2) },
        { key = '$', mods = p, action = act.ActivateTab(3) },
        { key = '%', mods = p, action = act.ActivateTab(4) },
        { key = '^', mods = p, action = act.ActivateTab(5) },
        { key = '&', mods = p, action = act.ActivateTab(6) },
        { key = '*', mods = p, action = act.ActivateTab(7) },
        { key = '(', mods = p, action = act.ActivateTab(-1) },
        -- Special characters:
        { key = "{", mods = p, action = act.MoveTabRelative(-1) },
        { key = "}", mods = p, action = act.MoveTabRelative(1) },
        { key = "\"", mods = p, action = act.SplitVertical },
        { key = "|", mods = p, action = act.SplitHorizontal },
        { key = "_", mods = p, action = act.DecreaseFontSize },
        { key = "+", mods = p, action = act.IncreaseFontSize },
        { key = ".", mods = p, action = act.ResetFontSize },
        { key = ".", mods = s, action = act.ReloadConfiguration },
        { key = "?", mods = p, action = act.Search({ Regex = "" }) },
        { key = 'Tab', mods = 'CTRL', action = act.ActivateTabRelative(1) },
        { key = 'Tab', mods = 'SHIFT|CTRL', action = act.ActivateTabRelative(-1) },
        { key = "Space", mods = s, action = act.CharSelect },
        { key = "Enter", mods = p, action = act.ToggleFullScreen },
        { key = "Enter", mods = s, action = act.ShowDebugOverlay },
        -- Nav keys:
        { key = "LeftArrow", mods = p, action = act.ActivatePaneDirection("Left") },
        { key = "DownArrow", mods = p, action = act.ActivatePaneDirection("Down") },
        { key = "UpArrow", mods = p, action = act.ActivatePaneDirection("Up") },
        { key = "RightArrow", mods = p, action = act.ActivatePaneDirection("Right") },
        { key = "LeftArrow", mods = s, action = act.AdjustPaneSize({ "Left", 1 }) },
        { key = "DownArrow", mods = s, action = act.AdjustPaneSize({ "Down", 1 }) },
        { key = "UpArrow", mods = s, action = act.AdjustPaneSize({ "Up", 1 }) },
        { key = "RightArrow", mods = s, action = act.AdjustPaneSize({ "Right", 1 }) },
        { key = "Home", mods = p, action = act.ScrollToTop },
        { key = "PageUp", mods = p, action = act.ScrollByPage(-1) },
        { key = "PageDown", mods = p, action = act.ScrollByPage(1) },
        { key = "End", mods = p, action = act.ScrollToBottom },
    }
end

function GENERATE_KEYS.gen_custom_key_tables()
    return {
        copy_mode = {
            { key = 'Tab', mods = 'NONE', action = act.CopyMode 'MoveForwardWord' },
            { key = 'Tab', mods = 'SHIFT', action = act.CopyMode 'MoveBackwardWord' },
            { key = 'Enter', mods = 'NONE', action = act.CopyMode 'MoveToStartOfNextLine' },
            { key = 'Escape', mods = 'NONE', action = act.CopyMode 'Close' },
            { key = 'Space', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Cell' } },
            { key = '$', mods = 'NONE', action = act.CopyMode 'MoveToEndOfLineContent' },
            { key = '$', mods = 'SHIFT', action = act.CopyMode 'MoveToEndOfLineContent' },
            { key = ',', mods = 'NONE', action = act.CopyMode 'JumpReverse' },
            { key = '0', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLine' },
            { key = ';', mods = 'NONE', action = act.CopyMode 'JumpAgain' },
            { key = 'F', mods = 'NONE', action = act.CopyMode{ JumpBackward = { prev_char = false } } },
            { key = 'F', mods = 'SHIFT', action = act.CopyMode{ JumpBackward = { prev_char = false } } },
            { key = 'G', mods = 'NONE', action = act.CopyMode 'MoveToScrollbackBottom' },
            { key = 'G', mods = 'SHIFT', action = act.CopyMode 'MoveToScrollbackBottom' },
            { key = 'H', mods = 'NONE', action = act.CopyMode 'MoveToViewportTop' },
            { key = 'H', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportTop' },
            { key = 'L', mods = 'NONE', action = act.CopyMode 'MoveToViewportBottom' },
            { key = 'L', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportBottom' },
            { key = 'M', mods = 'NONE', action = act.CopyMode 'MoveToViewportMiddle' },
            { key = 'M', mods = 'SHIFT', action = act.CopyMode 'MoveToViewportMiddle' },
            { key = 'O', mods = 'NONE', action = act.CopyMode 'MoveToSelectionOtherEndHoriz' },
            { key = 'O', mods = 'SHIFT', action = act.CopyMode 'MoveToSelectionOtherEndHoriz' },
            { key = 'T', mods = 'NONE', action = act.CopyMode{ JumpBackward = { prev_char = true } } },
            { key = 'T', mods = 'SHIFT', action = act.CopyMode{ JumpBackward = { prev_char = true } } },
            { key = 'V', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Line' } },
            { key = 'V', mods = 'SHIFT', action = act.CopyMode{ SetSelectionMode =  'Line' } },
            { key = '^', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLineContent' },
            { key = '^', mods = 'SHIFT', action = act.CopyMode 'MoveToStartOfLineContent' },
            { key = 'b', mods = 'NONE', action = act.CopyMode 'MoveBackwardWord' },
            { key = 'b', mods = 'ALT', action = act.CopyMode 'MoveBackwardWord' },
            { key = 'b', mods = 'CTRL', action = act.CopyMode 'PageUp' },
            { key = 'c', mods = 'CTRL', action = act.CopyMode 'Close' },
            { key = 'd', mods = 'CTRL', action = act.CopyMode{ MoveByPage = (0.5) } },
            { key = 'e', mods = 'NONE', action = act.CopyMode 'MoveForwardWordEnd' },
            { key = 'f', mods = 'NONE', action = act.CopyMode{ JumpForward = { prev_char = false } } },
            { key = 'f', mods = 'ALT', action = act.CopyMode 'MoveForwardWord' },
            { key = 'f', mods = 'CTRL', action = act.CopyMode 'PageDown' },
            { key = 'g', mods = 'NONE', action = act.CopyMode 'MoveToScrollbackTop' },
            { key = 'g', mods = 'CTRL', action = act.CopyMode 'Close' },
            { key = 'h', mods = 'NONE', action = act.CopyMode 'MoveLeft' },
            { key = 'j', mods = 'NONE', action = act.CopyMode 'MoveDown' },
            { key = 'k', mods = 'NONE', action = act.CopyMode 'MoveUp' },
            { key = 'l', mods = 'NONE', action = act.CopyMode 'MoveRight' },
            { key = 'm', mods = 'ALT', action = act.CopyMode 'MoveToStartOfLineContent' },
            { key = 'o', mods = 'NONE', action = act.CopyMode 'MoveToSelectionOtherEnd' },
            { key = 'q', mods = 'NONE', action = act.CopyMode 'Close' },
            { key = 't', mods = 'NONE', action = act.CopyMode{ JumpForward = { prev_char = true } } },
            { key = 'u', mods = 'CTRL', action = act.CopyMode{ MoveByPage = (-0.5) } },
            { key = 'v', mods = 'NONE', action = act.CopyMode{ SetSelectionMode =  'Cell' } },
            { key = 'v', mods = 'CTRL', action = act.CopyMode{ SetSelectionMode =  'Block' } },
            { key = 'w', mods = 'NONE', action = act.CopyMode 'MoveForwardWord' },
            { key = 'y', mods = 'NONE', action = act.Multiple{ { CopyTo =  'ClipboardAndPrimarySelection' }, { CopyMode =  'Close' } } },
            { key = 'PageUp', mods = 'NONE', action = act.CopyMode 'PageUp' },
            { key = 'PageDown', mods = 'NONE', action = act.CopyMode 'PageDown' },
            { key = 'End', mods = 'NONE', action = act.CopyMode 'MoveToEndOfLineContent' },
            { key = 'Home', mods = 'NONE', action = act.CopyMode 'MoveToStartOfLine' },
            { key = 'LeftArrow', mods = 'NONE', action = act.CopyMode 'MoveLeft' },
            { key = 'LeftArrow', mods = 'ALT', action = act.CopyMode 'MoveBackwardWord' },
            { key = 'RightArrow', mods = 'NONE', action = act.CopyMode 'MoveRight' },
            { key = 'RightArrow', mods = 'ALT', action = act.CopyMode 'MoveForwardWord' },
            { key = 'UpArrow', mods = 'NONE', action = act.CopyMode 'MoveUp' },
            { key = 'DownArrow', mods = 'NONE', action = act.CopyMode 'MoveDown' },
        },

        search_mode = {
            { key = 'Enter', mods = 'NONE', action = act.CopyMode 'PriorMatch' },
            { key = 'Escape', mods = 'NONE', action = act.CopyMode 'Close' },
            { key = 'n', mods = 'CTRL', action = act.CopyMode 'NextMatch' },
            { key = 'p', mods = 'CTRL', action = act.CopyMode 'PriorMatch' },
            { key = 'r', mods = 'CTRL', action = act.CopyMode 'CycleMatchType' },
            { key = 'u', mods = 'CTRL', action = act.CopyMode 'ClearPattern' },
            { key = 'PageUp', mods = 'NONE', action = act.CopyMode 'PriorMatchPage' },
            { key = 'PageDown', mods = 'NONE', action = act.CopyMode 'NextMatchPage' },
            { key = 'UpArrow', mods = 'NONE', action = act.CopyMode 'PriorMatch' },
            { key = 'DownArrow', mods = 'NONE', action = act.CopyMode 'NextMatch' },
        },
    }
end

return GENERATE_KEYS
